forgit: update to 25.07.0

diff --git a/local/bin/git-forgit b/local/bin/git-forgit
--- a/local/bin/git-forgit
+++ b/local/bin/git-forgit
@@ -28,10 +28,6 @@ if [[ "$higher_fzf_version" != "$installed_fzf_version" ]]; then
 fi
 
 # Set shell for fzf preview commands
-# Disable shellcheck for "which", because it suggests "command -v xxx" instead,
-# which is not a working replacement.
-# See https://github.com/koalaman/shellcheck/issues/1162
-# shellcheck disable=2230
 SHELL="$(which bash)"
 export SHELL
 
@@ -414,7 +410,7 @@ _forgit_show() {
         --bind=\"alt-t:transform:[[ ! \\\"\$FZF_PREVIEW_LABEL\\\" =~ 'Diff' ]] &&
                 echo 'change-preview-label( Diff )+refresh-preview' ||
                 echo 'change-preview-label( Commit Message )+refresh-preview'\"
-        $FORGIT_DIFF_FZF_OPTS
+        $FORGIT_SHOW_FZF_OPTS
         --prompt=\"${commit} > \"
     "
     _forgit_show_git_opts=()
@@ -759,25 +755,67 @@ _forgit_file_preview() {
 _forgit_fixup() {
     _forgit_inside_work_tree || return 1
     git diff --cached --quiet && echo 'Nothing to fixup: there are no staged changes.' && return 1
-    local opts graph quoted_files target_commit prev_commit
+    _forgit_edit_commit --fixup "$FORGIT_FIXUP_FZF_OPTS" "$FORGIT_FIXUP_GIT_OPTS" "$@"
+}
+
+_forgit_squash() {
+    _forgit_inside_work_tree || return 1
+    git diff --cached --quiet && echo 'Nothing to squash: there are no staged changes.' && return 1
+    _forgit_edit_commit --squash "$FORGIT_SQUASH_FZF_OPTS" "$FORGIT_SQUASH_GIT_OPTS" "$@"
+}
+
+_forgit_edit_commit() {
+    local action fzf_opts opts graph quoted_files target_commit prev_commit
+    action=$1
+    fzf_opts=$2
     graph=()
     [[ $_forgit_log_graph_enable == true ]] && graph=(--graph)
-    _forgit_fixup_git_opts=()
-    _forgit_parse_array _forgit_fixup_git_opts "$FORGIT_FIXUP_GIT_OPTS"
+    git_opts=()
+    _forgit_parse_array git_opts "$3"
+    shift 3
     quoted_files=$(_forgit_quote_files "$@")
     opts="
         $FORGIT_FZF_DEFAULT_OPTS
         +s +m --tiebreak=index
         --bind=\"ctrl-y:execute-silent($FORGIT yank_sha {})\"
         --preview=\"$FORGIT file_preview {} $quoted_files\"
-        $FORGIT_FIXUP_FZF_OPTS
+        $fzf_opts
     "
     target_commit=$(
         git log "${graph[@]}" --color=always --format="$_forgit_log_format" "$@" |
         _forgit_emojify |
         FZF_DEFAULT_OPTS="$opts" fzf |
         _forgit_extract_sha)
-    if [[ -n "$target_commit" ]] && git commit "${_forgit_fixup_git_opts[@]}" --fixup "$target_commit"; then
+    # GIT_EDITOR=: is needed to skip the editor
+    if [[ -n "$target_commit" ]] && GIT_EDITOR=: git commit "${git_opts[@]}" "$action" "$target_commit"; then
+        prev_commit=$(_forgit_previous_commit "$target_commit")
+        # rebase will fail if there are unstaged changes so --autostash is needed to temporarily stash them
+        # GIT_SEQUENCE_EDITOR=: is needed to skip the editor
+        GIT_SEQUENCE_EDITOR=: git rebase --autostash -i --autosquash "$prev_commit"
+    fi
+}
+
+_forgit_reword() {
+    _forgit_inside_work_tree || return 1
+    local opts graph quoted_files target_commit prev_commit
+    graph=()
+    [[ $_forgit_log_graph_enable == true ]] && graph=(--graph)
+    git_opts=()
+    _forgit_parse_array _forgit_reword_git_opts "$FORGIT_REWORD_GIT_OPTS"
+    quoted_files=$(_forgit_quote_files "$@")
+    opts="
+        $FORGIT_FZF_DEFAULT_OPTS
+        +s +m --tiebreak=index
+        --bind=\"ctrl-y:execute-silent($FORGIT yank_sha {})\"
+        --preview=\"$FORGIT file_preview {} $quoted_files\"
+        $FORGIT_REWORD_FZF_OPTS
+    "
+    target_commit=$(
+        git log "${graph[@]}" --color=always --format="$_forgit_log_format" "$@" |
+        _forgit_emojify |
+        FZF_DEFAULT_OPTS="$opts" fzf |
+        _forgit_extract_sha)
+    if [[ -n "$target_commit" ]] && git commit "${git_opts[@]}" --fixup=reword:"$target_commit"; then
         prev_commit=$(_forgit_previous_commit "$target_commit")
         # rebase will fail if there are unstaged changes so --autostash is needed to temporarily stash them
         # GIT_SEQUENCE_EDITOR=: is needed to skip the editor
@@ -849,10 +887,10 @@ _forgit_checkout_branch() {
     [[ -z "$branch" ]] && return 1
 
     # track the remote branch if possible
-    if [[ "$branch" == "remotes/origin/"* ]]; then
-        if git branch | grep -qw "${branch#remotes/origin/}"; then
+    if [[ "$branch" == "remotes/"* ]]; then
+        if git branch | grep -qw "${branch#remotes/*/}"; then
             # hack to force creating a new branch which tracks the remote if a local branch already exists
-            _forgit_git_checkout_branch -b "track/${branch#remotes/origin/}" --track "$branch"
+            _forgit_git_checkout_branch -b "track/${branch#remotes/*/}" --track "$branch"
         elif ! _forgit_git_checkout_branch --track "$branch" 2>/dev/null; then
             _forgit_git_checkout_branch "$branch"
         fi
@@ -1152,6 +1190,8 @@ public_commands=(
     "clean"
     "diff"
     "fixup"
+    "squash"
+    "reword"
     "ignore"
     "log"
     "reflog"
