forgit: update to 26.01.0

diff --git a/local/bin/git-forgit b/local/bin/git-forgit
--- a/local/bin/git-forgit
+++ b/local/bin/git-forgit
@@ -12,27 +12,7 @@
 # This gives users the choice to set aliases inside of their git config instead
 # of their shell config if they prefer.
 
-# Check if fzf is installed
-installed_fzf_version=$(fzf --version 2>/dev/null | awk '{print $1}')
-if [[ -z "$installed_fzf_version" ]]; then
-    echo "fzf is not installed. Please install fzf first."
-    exit 1
-fi
-
-# Check fzf version
-required_fzf_version="0.49.0"
-higher_fzf_version=$(printf '%s\n' "$required_fzf_version" "$installed_fzf_version" | sort -V | tail -n1)
-if [[ "$higher_fzf_version" != "$installed_fzf_version" ]]; then
-    echo "fzf version $required_fzf_version or higher is required. You have $installed_fzf_version."
-    exit 1
-fi
-
-# Set shell for fzf preview commands
-SHELL="$(which bash)"
-export SHELL
-
-# Get absolute forgit path
-FORGIT=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)/$(basename -- "${BASH_SOURCE[0]}")
+REQUIRED_FZF_VERSION="0.49.0"
 
 FORGIT_FZF_DEFAULT_OPTS="
 $FZF_DEFAULT_OPTS
@@ -186,6 +166,10 @@ _forgit_list_files() {
     git ls-files -z "$@" "$rootdir" | tr '\0' '\n' | uniq
 }
 
+_forgit_is_submodule() {
+    git submodule --quiet status "$1"
+}
+
 _forgit_log_preview() {
     local sha
     sha=$(echo "$1" | _forgit_extract_sha)
@@ -252,6 +236,14 @@ _forgit_reflog() {
     return $fzf_exit_code
 }
 
+_forgit_remove_status_from_diff_line() {
+    # Remove the status prefix from a diff line, e.g.
+    #   [M]     somefile
+    # becomes
+    #   somefile
+    sed 's/^[[:space:]]*\[[A-Z0-9]*\][[:space:]]*//'
+}
+
 _forgit_get_files_from_diff_line() {
     # Construct a null-terminated list of the filenames
     # The input looks like one of these lines:
@@ -264,13 +256,13 @@ _forgit_get_files_from_diff_line() {
     #   oldfile\0
     # We have to do a two-step sed -> tr pipe because OSX's sed implementation does
     # not support the null-character directly.
-    sed 's/^[[:space:]]*\[[A-Z0-9]*\][[:space:]]*//' | sed 's/  ->  /\n/' | tr '\n' '\0'
+    _forgit_remove_status_from_diff_line | sed 's/  ->  /\n/' | tr '\n' '\0'
 }
 
 _forgit_get_single_file_from_diff_line() {
     # Similar to the function above, but only gets a single file from a single line
     # Gets the new name of renamed files
-    sed 's/^[[:space:]]*\[[A-Z0-9]*\][[:space:]]*//' | sed 's/.*->  //'
+    _forgit_remove_status_from_diff_line | sed 's/.*->  //'
 }
 
 _forgit_exec_diff() {
@@ -430,10 +422,12 @@ _forgit_show() {
 
 _forgit_add_preview() {
     file=$(echo "$1" | _forgit_get_single_file_from_add_line)
-    # $file can be a directory when status.showUntrackedFiles is explicitly set to 'normal'
-    # In this case, show the content of the directory and return
-    [ -d "$file" ] && eval "$_forgit_dir_view \"$file\"" && return 0
-
+    # $file can be a directory when status.showUntrackedFiles is set to 'normal'
+    # When this is the case and the directory is not a submodule show the content of the directory and return
+    if [[ -d "$file"  ]] && ! _forgit_is_submodule "$file"; then
+        eval "$_forgit_dir_view \"$file\""
+        return 0
+    fi
     if (git status -s -- "$file" | grep '^??') &>/dev/null; then  # diff with /dev/null for untracked files
         git diff --color=always --no-index -- /dev/null "$file" | _forgit_pager diff | sed '2 s/added:/untracked:/'
     else
@@ -620,21 +614,28 @@ _forgit_clean_preview() {
     fi
 }
 
-# git clean selector
-_forgit_clean() {
-    _forgit_inside_work_tree || return 1
-    _forgit_contains_non_flags "$@" && { git clean -q "$@"; return $?; }
-    local files opts
-    _forgit_clean_git_opts=()
-    _forgit_parse_array _forgit_clean_git_opts "$FORGIT_CLEAN_GIT_OPTS"
+_forgit_clean_select_files() {
+    local opts
     opts="
         $FORGIT_FZF_DEFAULT_OPTS
         --preview=\"$FORGIT clean_preview {}\"
         -m -0
         $FORGIT_CLEAN_FZF_OPTS
     "
+    _forgit_clean_list_files_opts=()
+    _forgit_parse_array _forgit_clean_list_files_opts "$FORGIT_CLEAN_LIST_FILES_OPTS"
     # Note: Postfix '/' in directory path should be removed. Otherwise the directory itself will not be removed.
-    files=$(git -c core.quotePath=false clean -xdffn "$@"| sed 's/^Would remove //' | FZF_DEFAULT_OPTS="$opts" fzf |sed 's#/$##')
+    _forgit_list_files --others "${_forgit_clean_list_files_opts[@]}" "$@" | FZF_DEFAULT_OPTS="$opts" fzf | sed 's#/$##'
+}
+
+# git clean selector
+_forgit_clean() {
+    _forgit_inside_work_tree || return 1
+    _forgit_contains_non_flags "$@" && { git clean -q "$@"; return $?; }
+    local files
+    _forgit_clean_git_opts=()
+    _forgit_parse_array _forgit_clean_git_opts "$FORGIT_CLEAN_GIT_OPTS"
+    files=$(_forgit_clean_select_files "$@")
     [[ -n "$files" ]] && echo "$files" | tr '\n' '\0' | xargs -0 -I% git clean "${_forgit_clean_git_opts[@]}" -xdff '%' && git status --short && return
     echo 'Nothing to clean.'
 }
@@ -847,6 +848,7 @@ _forgit_checkout_file() {
     _forgit_inside_work_tree || return 1
     local files opts
     _forgit_contains_non_flags "$@" && { _forgit_git_checkout_file "$@"; return $?; }
+    [[ $(_forgit_list_files --modified | wc -l) -eq 0 ]] && echo 'Nothing to checkout.' && return 1
     opts="
         $FORGIT_FZF_DEFAULT_OPTS
         -m -0
@@ -908,6 +910,52 @@ _forgit_checkout_branch() {
     fi
 }
 
+_forgit_git_switch_branch() {
+    _forgit_switch_branch_git_opts=()
+    _forgit_parse_array _forgit_switch_branch_git_opts "$FORGIT_SWITCH_BRANCH_GIT_OPTS"
+    git switch "${_forgit_switch_branch_git_opts[@]}" "$@"
+}
+
+_forgit_switch_branch() {
+    _forgit_inside_work_tree || return 1
+    # if called with arguments, check if branch exists, else create a new one
+    if [[ $# -ne 0 ]]; then
+        if [[ "$*" == "-" ]] || git show-branch "$@" &>/dev/null; then
+            git switch "$@"
+        else
+            git switch -c "$@"
+        fi
+        checkout_status=$?
+        git status --short
+        return $checkout_status
+    fi
+
+    local opts branch
+    opts="
+        $FORGIT_FZF_DEFAULT_OPTS
+        +s +m --tiebreak=index --header-lines=1
+        --preview=\"$FORGIT branch_preview {1}\"
+        $FORGIT_SWITCH_BRANCH_FZF_OPTS
+        "
+    _forgit_switch_branch_branch_git_opts=()
+    _forgit_parse_array _forgit_switch_branch_branch_git_opts "$FORGIT_SWITCH_BRANCH_BRANCH_GIT_OPTS"
+    branch="$(git branch --color=always "${_forgit_switch_branch_branch_git_opts[@]:---all}" | LC_ALL=C sort -k1.1,1.1 -rs |
+              FZF_DEFAULT_OPTS="$opts" fzf | awk '{print $1}')"
+    [[ -z "$branch" ]] && return 1
+
+    # track the remote branch if possible
+    if [[ "$branch" == "remotes/"* ]]; then
+        if git branch | grep -qw "${branch#remotes/*/}"; then
+            # hack to force creating a new branch which tracks the remote if a local branch already exists
+            _forgit_git_switch_branch --create "track/${branch#remotes/*/}" --track "$branch"
+        elif ! _forgit_git_switch_branch --track "$branch" 2>/dev/null; then
+            _forgit_git_switch_branch "$branch"
+        fi
+    else
+        _forgit_git_switch_branch "$branch"
+    fi
+}
+
 _forgit_git_checkout_tag() {
     _forgit_checkout_tag_git_opts=()
     _forgit_parse_array _forgit_checkout_tag_git_opts "$FORGIT_CHECKOUT_TAG_GIT_OPTS"
@@ -917,8 +965,9 @@ _forgit_git_checkout_tag() {
 # git checkout-tag selector
 _forgit_checkout_tag() {
     _forgit_inside_work_tree || return 1
-    local opts
+    local opts tag
     [[ $# -ne 0 ]] && { _forgit_git_checkout_tag "$@"; return $?; }
+    [[ $(git tag -l | wc -l) -eq 0 ]] && echo 'Nothing to checkout: there are no tags.' && return 1
     opts="
         $FORGIT_FZF_DEFAULT_OPTS
         +s +m --tiebreak=index
@@ -1185,12 +1234,60 @@ _forgit_paths_list() {
     find "$path" -name "*$ext" -print |sed -e "s#$ext\$##" -e 's#.*/##' -e '/^$/d' | sort -fu
 }
 
-public_commands=(
+check_prequisites() {
+    local installed_fzf_version
+    local higher_fzf_version
+
+    # Check if fzf is installed
+    installed_fzf_version=$(fzf --version 2>/dev/null | awk '{print $1}')
+    if [[ -z "$installed_fzf_version" ]]; then
+        echo "fzf is not installed. Please install fzf first."
+        exit 1
+    fi
+
+    # Check fzf version
+    higher_fzf_version=$(printf '%s\n' "$REQUIRED_FZF_VERSION" "$installed_fzf_version" | sort -V | tail -n1)
+    if [[ "$higher_fzf_version" != "$installed_fzf_version" ]]; then
+        echo "fzf version $REQUIRED_FZF_VERSION or higher is required. You have $installed_fzf_version."
+        exit 1
+    fi
+}
+
+main() {
+    local cmd="$1"
+    shift
+
+    check_prequisites
+
+    # Set shell for fzf preview commands
+    SHELL="$(which bash)"
+    export SHELL
+
+    # Get absolute forgit path
+    FORGIT=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)/$(basename -- "${BASH_SOURCE[0]}")
+
+    # shellcheck disable=SC2076
+    if [[ ! " ${PUBLIC_COMMANDS[*]} " =~ " ${cmd} " ]] && [[ ! " ${PRIVATE_COMMANDS[*]} " =~ " ${cmd} " ]]; then
+        if [[ -z "$cmd" ]]; then
+            printf "forgit: missing command\n\n"
+        else
+            printf "forgit: '%s' is not a valid forgit command.\n\n" "$cmd"
+        fi
+        printf "The following commands are supported:\n"
+        printf "\t%s\n" "${PUBLIC_COMMANDS[@]}"
+        exit 1
+    fi
+
+    _forgit_"${cmd}" "$@"
+}
+
+PUBLIC_COMMANDS=(
     "add"
     "attributes"
     "blame"
     "branch_delete"
     "checkout_branch"
+    "switch_branch"
     "checkout_commit"
     "checkout_file"
     "checkout_tag"
@@ -1212,7 +1309,7 @@ public_commands=(
     "stash_push"
 )
 
-private_commands=(
+PRIVATE_COMMANDS=(
     "add_preview"
     "blame_preview"
     "branch_preview"
@@ -1243,19 +1340,10 @@ private_commands=(
     "pager"
 )
 
-cmd="$1"
-shift
-
-# shellcheck disable=SC2076
-if [[ ! " ${public_commands[*]} " =~ " ${cmd} " ]] && [[ ! " ${private_commands[*]} " =~ " ${cmd} " ]]; then
-    if [[ -z "$cmd" ]]; then
-        printf "forgit: missing command\n\n"
-    else
-        printf "forgit: '%s' is not a valid forgit command.\n\n" "$cmd"
-    fi
-    printf "The following commands are supported:\n"
-    printf "\t%s\n" "${public_commands[@]}"
-    exit 1
+# Check if the script is being sourced. This is necessary for unit tests where
+# we do not want to execute the main function.
+if [[ "${BASH_SOURCE[0]}" != "$0" ]]; then
+    return 0
 fi
 
-_forgit_"${cmd}" "$@"
+main "${@}"
